#requires -Version 7.2
param([ValidateSet('All','Validation','Logs','Git','Recovery','Bootstrap')][string]$Suite='All')
$ErrorActionPreference='Stop'
$package=Split-Path $PSScriptRoot -Parent
$runRoot=Join-Path (Join-Path (Get-Location) 'work/publisher-tests') ('StudyPublisherTests-'+[guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $runRoot | Out-Null
$script:passed=0; $script:failed=0
function Check($Name,[scriptblock]$Action){try{& $Action; $script:passed++;Write-Host "PASS $Name"}catch{$script:failed++;Write-Host "FAIL $Name : $($_.Exception.Message)";Write-Host $_.ScriptStackTrace}}
function Assert($Condition,$Message='assertion failed'){if(-not $Condition){throw $Message}}
function Reject([scriptblock]$Action,$Pattern=''){ $err=$null;try{& $Action | Out-Null}catch{$err=$_.Exception.Message}; Assert ($null -ne $err) 'expected rejection'; if($err -match 'not recognized|not found|cannot find'){throw $err};if($Pattern){Assert ($err -match $Pattern) "wrong rejection: $err"}}
function WriteText($Path,$Text){[IO.Directory]::CreateDirectory((Split-Path $Path -Parent))|Out-Null;[IO.File]::WriteAllText($Path,$Text,[Text.UTF8Encoding]::new($false))}
function Hash($Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Fixture {
 $b=Join-Path $runRoot ([guid]::NewGuid().ToString('N'));$src=Join-Path $b 'source';$repo=Join-Path $b 'repo';$log=Join-Path $b 'logs';[IO.Directory]::CreateDirectory($src)|Out-Null;[IO.Directory]::CreateDirectory($repo)|Out-Null
 $f=Join-Path $src '中文 笔记.md';WriteText $f "# 学习笔记`n`n这是已审核的一般笔记，用于验证上传流程，内容并不作为章节型笔记。`n"
 $c=[pscustomobject]@{SchemaVersion=1;RepositoryRoot=$repo;ExpectedRemote='';SourceRoots=@($src);AllowedSubjects=@('数学');LogRoot=$log;NetworkTimeoutSeconds=30}
 $q=[pscustomobject]@{SchemaVersion=1;ReviewCompleted=$true;Entries=@([pscustomobject]@{SourcePath=$f;DestinationPath='数学/中文 笔记.md';ReviewedSha256=(Hash $f);Kind='general-note'})}
 [pscustomobject]@{Base=$b;Source=$src;Repo=$repo;File=$f;Config=$c;Request=$q}
}
if($Suite -in @('All','Validation')){
 Check 'ModulesLoad' {Import-Module (Join-Path $package 'scripts/Validation.psm1') -Force -Global -DisableNameChecking}
 Check 'AcceptChineseSpacePath' {$f=Fixture;$s=Get-PublishSnapshot $f.Config $f.Request; Assert ($s.Entries.Count -eq 1); Assert ($s.Entries[0].DestinationPath -eq '数学/中文 笔记.md')}
 Check 'RejectOutOfRoot' {$f=Fixture;$f.Request.Entries[0].SourcePath=$PSCommandPath;Reject {Get-PublishSnapshot $f.Config $f.Request} '来源|source'}
 Check 'RejectTraversalDestination' {$f=Fixture;$f.Request.Entries[0].DestinationPath='../泄露.md';Reject {Get-PublishSnapshot $f.Config $f.Request}}
 Check 'RejectChangedReviewHash' {$f=Fixture;Add-Content -LiteralPath $f.File '更改';Reject {Get-PublishSnapshot $f.Config $f.Request} '摘要|hash'}
 Check 'RejectUnreviewed' {$f=Fixture;$f.Request.ReviewCompleted=$false;Reject {Get-PublishSnapshot $f.Config $f.Request}}
 Check 'RejectEmptyOrInvalidUtf8' {$f=Fixture;[IO.File]::WriteAllBytes($f.File,[byte[]]@(255,255));$f.Request.Entries[0].ReviewedSha256=Hash $f.File;Reject {Get-PublishSnapshot $f.Config $f.Request};WriteText $f.File '';$f.Request.Entries[0].ReviewedSha256=Hash $f.File;Reject {Get-PublishSnapshot $f.Config $f.Request}}
 Check 'RejectDuplicateCaseCollision' {$f=Fixture;$e=$f.Request.Entries[0]|ConvertTo-Json|ConvertFrom-Json;$e.DestinationPath='数学/中文 笔记.MD';$f.Request.Entries+= $e;Reject {Get-PublishSnapshot $f.Config $f.Request}}
 Check 'RejectExerciseWithoutKnowledge' {$f=Fixture;WriteText $f.File "# 章节`n## 一、学习`n### 本章路线`n本章要解决的问题：理解概念。本章学完应会：解释概念。`n### 学习单元`n##### 小练习：算题`n### 本章小结`n### 本章练习与检验";$f.Request.Entries[0].Kind='chapter-note';$f.Request.Entries[0].ReviewedSha256=Hash $f.File;Reject {Get-PublishSnapshot $f.Config $f.Request} '知识|讲解'}
 Check 'RejectBareFormulaUnit' {$f=Fixture;WriteText $f.File "# 章节`n## 一、学习`n### 本章路线`n本章要解决的问题：理解概念。本章学完应会：解释概念。`n### 学习单元`n#### 概念`n`$x=1`$`n##### 小练习：算题`n### 本章小结`n### 本章练习与检验";$f.Request.Entries[0].Kind='chapter-note';$f.Request.Entries[0].ReviewedSha256=Hash $f.File;Reject {Get-PublishSnapshot $f.Config $f.Request}}
 Check 'AcceptCompleteChapter' {$f=Fixture;$body=('概率用来描述随机试验中事件发生可能性的大小，先明确样本空间和事件，再检查事件之间的包含关系。'*2);WriteText $f.File "# 章节`n## 一、概率`n### 本章路线`n本章要解决的问题：理解概率。本章学完应会：解释概念。`n### 学习单元`n#### 样本空间`n$body`n##### 小练习：事件`n按上述定义判断。`n### 本章小结`n回收概念。`n### 本章练习与检验`n比较事件。";$f.Request.Entries[0].Kind='chapter-note';$f.Request.Entries[0].ReviewedSha256=Hash $f.File;Assert ((Get-PublishSnapshot $f.Config $f.Request).Entries.Count -eq 1)}
 Check 'GeneralReadmeNotChapterChecked' {$f=Fixture;Assert ((Get-PublishSnapshot $f.Config $f.Request).Entries.Count -eq 1)}
 Check 'MissingLocalImage' {$f=Fixture;Add-Content $f.File '![图](images/missing.png)';$f.Request.Entries[0].ReviewedSha256=Hash $f.File;Reject {Get-PublishSnapshot $f.Config $f.Request} '图片|引用|不存在'}
 Check 'ReferencedImageIncluded' {$f=Fixture;$im=Join-Path $f.Source 'images/图.png';[IO.Directory]::CreateDirectory((Split-Path $im))|Out-Null;[IO.File]::WriteAllBytes($im,[byte[]]@(137,80,78,71));Add-Content $f.File '![图](images/图.png)';$f.Request.Entries[0].ReviewedSha256=Hash $f.File;Reject {Get-PublishSnapshot $f.Config $f.Request};$f.Request.Entries+= [pscustomobject]@{SourcePath=$im;DestinationPath='数学/images/图.png';ReviewedSha256=(Hash $im);Kind='image'};Assert ((Get-PublishSnapshot $f.Config $f.Request).Entries.Count -eq 2)}
 Check 'RejectLikelyCredential' {$f=Fixture;WriteText $f.File ('# 内容'+"`n"+'token = '+'ghp_'+('A'*36));$f.Request.Entries[0].ReviewedSha256=Hash $f.File;Reject {Get-PublishSnapshot $f.Config $f.Request} '凭据|secret'}
 Check 'ImageOutsideSourceRoot' {$f=Fixture;$outside=Join-Path $f.Base 'outside.png';[IO.File]::WriteAllBytes($outside,[byte[]]@(1,2));Add-Content $f.File '![图](../outside.png)';$f.Request.Entries[0].ReviewedSha256=Hash $f.File;Reject {Get-PublishSnapshot $f.Config $f.Request} '越界'}
 Check 'RejectActiveSvg' {$f=Fixture;$svg=Join-Path $f.Source '图.svg';WriteText $svg '<svg><script>alert(1)</script></svg>';$f.Request.Entries+= [pscustomobject]@{SourcePath=$svg;DestinationPath='数学/图.svg';ReviewedSha256=(Hash $svg);Kind='image'};Reject {Get-PublishSnapshot $f.Config $f.Request}}
 Check 'NewRequestCliCollectsImages' {$f=Fixture;$f.Config.ExpectedRemote='https://github.com/frredomerror91-netizen/HitszCourseNote.git';$cfg=Join-Path $f.Base 'cfg.json';$f.Config|ConvertTo-Json -Depth 5|Set-Content $cfg;[IO.File]::WriteAllBytes((Join-Path $f.Source '图.png'),[byte[]]@(137,80,78,71));Add-Content $f.File '![图](图.png)';$req=Join-Path $f.Repo '.publish-state/request.json';$out=& pwsh -NoProfile -File (Join-Path $package 'scripts/New-PublishRequest.ps1') -ConfigPath $cfg -Notes $f.File -Subject 数学 -Kind general-note -ReviewCompleted -RequestPath $req;Assert ($LASTEXITCODE -eq 0) ($out -join ';');$q=Get-Content $req -Raw|ConvertFrom-Json;Assert ($q.Entries.Count -eq 2)}
 Check 'RejectReparseAncestor' {$f=Fixture;$outside=Join-Path $f.Base 'outside';[IO.Directory]::CreateDirectory($outside)|Out-Null;WriteText (Join-Path $outside 'note.md') '# outside';$link=Join-Path $f.Source 'junction';New-Item -ItemType Junction -Path $link -Target $outside|Out-Null;$f.Request.Entries[0].SourcePath=Join-Path $link 'note.md';$f.Request.Entries[0].ReviewedSha256=Hash $f.Request.Entries[0].SourcePath;Reject {Get-PublishSnapshot $f.Config $f.Request} '链接|reparse'}
}
if($Suite -in @('All','Logs')){
 Check 'LogModulesLoad' {Import-Module (Join-Path $package 'scripts/Validation.psm1') -Force -Global -DisableNameChecking;Import-Module (Join-Path $package 'scripts/PublishLogs.psm1') -Force -Global -DisableNameChecking}
 Check 'MergeSameDateOnce' {$f=Fixture;$s=Get-PublishSnapshot $f.Config $f.Request;$p=Get-PublishLogPlan $f.Config $s;Write-PublishLogPlan $p|Out-Null;$p=Get-PublishLogPlan $f.Config $s;Write-PublishLogPlan $p|Out-Null;$text=Get-Content (Join-Path $f.Repo 'CHANGELOG.md') -Raw;Assert (([regex]::Matches($text,'中文 笔记.md')).Count -eq 1)}
 Check 'PreserveOtherProjectHistory' {$f=Fixture;WriteText (Join-Path $f.Config.LogRoot 'DAILY_CHANGELOG.md') "# 总日志`n## 2020-01-01`n旧项目不可丢失。`n";$s=Get-PublishSnapshot $f.Config $f.Request;Write-PublishLogPlan (Get-PublishLogPlan $f.Config $s)|Out-Null;Assert ((Get-Content (Join-Path $f.Config.LogRoot 'DAILY_CHANGELOG.md') -Raw).Contains('旧项目不可丢失。'))}
 Check 'ConcurrentLogEditStops' {$f=Fixture;$s=Get-PublishSnapshot $f.Config $f.Request;$p=Get-PublishLogPlan $f.Config $s;WriteText $p.Files[0].Path '其他聊天的新内容';Reject {Write-PublishLogPlan $p} '冲突|变化'}
 Check 'LogWriteFailureBlocksCommit' {$f=Fixture;WriteText $f.Config.LogRoot '不能作为目录';$s=Get-PublishSnapshot $f.Config $f.Request;Reject {Write-PublishLogPlan (Get-PublishLogPlan $f.Config $s)}}
 Check 'DryRunLogPlanWritesNothing' {$f=Fixture;$s=Get-PublishSnapshot $f.Config $f.Request;$p=Get-PublishLogPlan $f.Config $s;Assert ($p.Files.Count -ge 3);Assert (-not(Test-Path (Join-Path $f.Repo 'CHANGELOG.md')));Assert (-not(Test-Path $f.Config.LogRoot))}
 Check 'ClassifiesNewAndModifiedLogs' {$f=Fixture;$s=Get-PublishSnapshot $f.Config $f.Request;$p=Get-PublishLogPlan $f.Config $s;Write-PublishLogPlan $p|Out-Null;Assert ((Get-Content (Join-Path $f.Repo 'CHANGELOG.md') -Raw) -match '### 新增')}
 Check 'ExternalLogNeverStaged' {$f=Fixture;$s=Get-PublishSnapshot $f.Config $f.Request;$p=Get-PublishLogPlan $f.Config $s;Assert ($p.RepositoryFiles.Count -eq 1);Assert ($p.RepositoryFiles[0] -eq 'CHANGELOG.md')}
}
function G($Root,[string[]]$ArgsList){$r=Invoke-GitChecked $Root $ArgsList 30;if($r.ExitCode){throw "git failed $($ArgsList -join ' '): $($r.Stderr)"};$r.Stdout.Trim()}
function GitFixture{
 $f=Fixture;$remote=Join-Path $f.Base 'remote.git';G $f.Base @('init','--bare',$remote)|Out-Null;G $f.Repo @('init','-b','main')|Out-Null;G $f.Repo @('config','user.name','Test Author')|Out-Null;G $f.Repo @('config','user.email','test@example.invalid')|Out-Null
 WriteText (Join-Path $f.Repo '.gitignore') ".publish-state/`npublisher.local.json`n";G $f.Repo @('add','--','.gitignore')|Out-Null;G $f.Repo @('commit','-m','seed')|Out-Null;G $f.Repo @('remote','add','origin',$remote)|Out-Null;G $f.Repo @('push','-u','origin','main')|Out-Null;$f.Config.ExpectedRemote=$remote;$f
}
if($Suite -in @('All','Git','Recovery')){
 Check 'GitModulesLoad' {Import-Module (Join-Path $package 'scripts/Validation.psm1') -Global -Force -DisableNameChecking;Import-Module (Join-Path $package 'scripts/PublishLogs.psm1') -Global -Force -DisableNameChecking;Import-Module (Join-Path $package 'scripts/GitPublish.psm1') -Global -Force -DisableNameChecking}
 if($Suite -in @('All','Git')){
 Check 'OnlyManifestFilesCommitted' {$f=GitFixture;WriteText (Join-Path $f.Repo 'unrelated.md') 'private unrelated';$s=Get-PublishSnapshot $f.Config $f.Request;$r=Invoke-StudyPublish $f.Config $s;Assert ($r.Status -eq 'Pushed') ($r.Errors -join ';');$files=G $f.Repo @('diff-tree','--no-commit-id','--name-only','-r','HEAD');Assert ($files -match 'CHANGELOG.md');Assert ($files -notmatch 'unrelated');Assert ((G $f.Repo @('rev-parse','HEAD')) -eq (G $f.Repo @('rev-parse','origin/main')))}
 Check 'RejectExistingIndex' {$f=GitFixture;WriteText (Join-Path $f.Repo 'other.txt') 'other';G $f.Repo @('add','other.txt')|Out-Null;$r=Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request);Assert ($r.Status -eq 'Blocked');Assert ((G $f.Repo @('diff','--cached','--name-only')) -eq 'other.txt')}
 Check 'RejectWrongRootRemoteBranch' {$f=GitFixture;$f.Config.ExpectedRemote='wrong';Assert ((Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request)).Status -eq 'Blocked');$f.Config.ExpectedRemote=Join-Path $f.Base 'remote.git';G $f.Repo @('checkout','-b','other')|Out-Null;Assert ((Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request)).Status -eq 'Blocked')}
 Check 'RejectAheadHistory' {$f=GitFixture;WriteText (Join-Path $f.Repo 'old.txt') 'old';G $f.Repo @('add','old.txt')|Out-Null;G $f.Repo @('commit','-m','unrelated ahead')|Out-Null;Assert ((Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request)).Status -eq 'Blocked')}
 Check 'SecondPublisherBlockedByLock' {$f=GitFixture;$state=Join-Path $f.Repo '.publish-state';[IO.Directory]::CreateDirectory($state)|Out-Null;$lock=[IO.File]::Open((Join-Path $state 'publisher.lock'),[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);try{Assert ((Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request)).Status -eq 'Blocked')}finally{$lock.Dispose()}}
 Check 'GenerateInsideClonePublishesReviewedFile' {$f=GitFixture;$note=Join-Path $f.Repo '数学/中文 笔记.md';WriteText $note ([IO.File]::ReadAllText($f.File));$f.Config.SourceRoots+= $f.Repo;$f.Request.Entries[0].SourcePath=$note;$f.Request.Entries[0].ReviewedSha256=Hash $note;$r=Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request);Assert ($r.Status -eq 'Pushed') ($r.Errors -join ';')}
 Check 'NoChangeNoCommit' {$f=GitFixture;$s=Get-PublishSnapshot $f.Config $f.Request;$r=Invoke-StudyPublish $f.Config $s;Assert ($r.Status -eq 'Pushed');$id=G $f.Repo @('rev-parse','HEAD');$r=Invoke-StudyPublish $f.Config $s;Assert ($r.Status -eq 'NoChange');Assert ($id -eq (G $f.Repo @('rev-parse','HEAD')))}
 Check 'DryRunChangesNothing' {$f=GitFixture;$id=G $f.Repo @('rev-parse','HEAD');$r=Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request) -DryRun;Assert ($r.Status -eq 'DryRun');Assert (-not(Test-Path (Join-Path $f.Repo '.publish-state')));Assert (-not(Test-Path (Join-Path $f.Repo 'CHANGELOG.md')));Assert ($id -eq (G $f.Repo @('rev-parse','HEAD')))}
 Check 'ConcurrentInputEditStops' {$f=GitFixture;$s=Get-PublishSnapshot $f.Config $f.Request;Add-Content $f.File 'new';$r=Invoke-StudyPublish $f.Config $s;Assert ($r.Status -eq 'Blocked');Assert (-not(Test-Path (Join-Path $f.Repo '数学')))}
 Check 'CommitHookMutationStopsPush' {$f=GitFixture;WriteText (Join-Path $f.Repo 'unrelated.txt') 'private';WriteText (Join-Path $f.Repo '.git/hooks/pre-commit') "#!/bin/sh`ngit add unrelated.txt`n";$r=Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request);Assert ($r.Status -eq 'CommittedNotPushed');Assert ((G $f.Repo @('rev-parse','HEAD')) -ne (G $f.Repo @('rev-parse','origin/main')))}
 Check 'RejectDivergedOrBehindHistory' {$f=GitFixture;$peer=Join-Path $f.Base 'peer';G $f.Base @('clone',$f.Config.ExpectedRemote,$peer)|Out-Null;G $peer @('checkout','-b','main','origin/main')|Out-Null;G $peer @('config','user.name','Test Author')|Out-Null;G $peer @('config','user.email','test@example.invalid')|Out-Null;WriteText (Join-Path $peer 'remote.txt') 'remote';G $peer @('add','remote.txt')|Out-Null;G $peer @('commit','-m','remote advanced')|Out-Null;G $peer @('push','origin','main')|Out-Null;Assert ((Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request)).Status -eq 'Blocked');WriteText (Join-Path $f.Repo 'local.txt') 'local';G $f.Repo @('add','local.txt')|Out-Null;G $f.Repo @('commit','-m','local diverged')|Out-Null;Assert ((Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request)).Status -eq 'Blocked')}
 Check 'RejectIgnoredDestination' {$f=GitFixture;Add-Content (Join-Path $f.Repo '.gitignore') '数学/';$r=Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request);Assert ($r.Status -eq 'Blocked')}
 }
 if($Suite -in @('All','Recovery')){
 Check 'PushDeniedKeepsCommitAndRetryNoDuplicate' {$f=GitFixture;$hook=Join-Path $f.Config.ExpectedRemote 'hooks/pre-receive';WriteText $hook "#!/bin/sh`nexit 1`n";$r=Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request);Assert ($r.Status -eq 'CommittedNotPushed') ($r.Errors -join ';');$id=G $f.Repo @('rev-parse','HEAD');$receipt=Get-Content (Join-Path $f.Repo '.publish-state/last-publish.json') -Raw|ConvertFrom-Json;WriteText $hook "#!/bin/sh`nexit 0`n";$again=Retry-StudyPush $f.Config $receipt;Assert ($again.Status -eq 'Pushed') ($again.Errors -join ';');Assert ($id -eq (G $f.Repo @('rev-parse','HEAD')));$again=Retry-StudyPush $f.Config $receipt;Assert ($again.Status -eq 'Pushed')}
 Check 'RetryRejectsExtraLocalCommit' {$f=GitFixture;WriteText (Join-Path $f.Config.ExpectedRemote 'hooks/pre-receive') "#!/bin/sh`nexit 1`n";$r=Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request);Assert ($r.Status -eq 'CommittedNotPushed');$rec=Get-Content (Join-Path $f.Repo '.publish-state/last-publish.json') -Raw|ConvertFrom-Json;WriteText (Join-Path $f.Repo 'unwanted.txt') 'private';G $f.Repo @('add','unwanted.txt')|Out-Null;G $f.Repo @('commit','-m','extra')|Out-Null;Assert ((Retry-StudyPush $f.Config $rec).Status -eq 'Blocked')}
 Check 'TimeoutAfterAcceptedPush' {$f=GitFixture;& (Get-Module GitPublish) {$script:SimulateAcceptedTimeout=$true};try{$r=Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request);Assert ($r.Status -eq 'Pushed') ($r.Errors -join ';')}finally{& (Get-Module GitPublish) {$script:SimulateAcceptedTimeout=$false}}}
 Check 'RemoteAdvancedBeforePush' {$f=GitFixture;$peer=Join-Path $f.Base 'peer';G $f.Base @('clone',$f.Config.ExpectedRemote,$peer)|Out-Null;G $peer @('checkout','-b','main','origin/main')|Out-Null;G $peer @('config','user.name','Test Author')|Out-Null;G $peer @('config','user.email','test@example.invalid')|Out-Null;WriteText (Join-Path $peer 'other.txt') 'remote';G $peer @('add','other.txt')|Out-Null;G $peer @('commit','-m','racer')|Out-Null;G $peer @('push','origin','HEAD:refs/heads/racer')|Out-Null;$remote=$f.Config.ExpectedRemote.Replace('\','/');WriteText (Join-Path $f.Repo '.git/hooks/pre-push') ("#!/bin/sh`ngit --git-dir='"+$remote+"' update-ref refs/heads/main refs/heads/racer`n");$r=Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request);Assert ($r.Status -eq 'CommittedNotPushed') ($r.Errors -join ';')}
 Check 'ReceiptWriteFailureAfterCommit' {$f=GitFixture;WriteText (Join-Path $f.Repo '.publish-state/last-publish.json') 'preexisting';& (Get-Module GitPublish) {$script:SimulateReceiptFailure=$true};try{$r=Invoke-StudyPublish $f.Config (Get-PublishSnapshot $f.Config $f.Request);Assert ($r.Status -eq 'CommittedNotPushed');Assert ($r.CommitId);Assert ((G $f.Repo @('rev-parse','HEAD')) -ne (G $f.Repo @('rev-parse','origin/main')))}finally{& (Get-Module GitPublish) {$script:SimulateReceiptFailure=$false}}}
 }
}
if($Suite -in @('All','Bootstrap')){
 Check 'BootstrapModulesLoad' {Import-Module (Join-Path $package 'scripts/GitPublish.psm1') -Global -Force -DisableNameChecking;Import-Module (Join-Path $package 'scripts/Bootstrap.psm1') -Global -Force -DisableNameChecking}
 Check 'BootstrapDryRunNoDirectory' {$f=Fixture;$r=Install-StudyPublisher -Destination (Join-Path $f.Base 'new-clone') -RemoteUrl 'https://github.com/frredomerror91-netizen/HitszCourseNote.git' -ToolPackagePath $package -DryRun;Assert ($r.Status -eq 'DryRun');Assert (-not(Test-Path (Join-Path $f.Base 'new-clone')))}
 Check 'ExistingDestinationUntouched' {$f=Fixture;WriteText (Join-Path $f.Repo 'keep.txt') 'keep';Reject {Install-StudyPublisher -Destination $f.Repo -RemoteUrl 'https://github.com/frredomerror91-netizen/HitszCourseNote.git' -ToolPackagePath $package -Execute};Assert ((Get-Content (Join-Path $f.Repo 'keep.txt')) -eq 'keep')}
 Check 'BootstrapOnlyToolsAndExcludedState' {$f=Fixture;$remote=Join-Path $f.Base 'empty.git';G $f.Base @('init','--bare',$remote)|Out-Null;$target=Join-Path $f.Base 'new';$r=Install-StudyPublisher -Destination $target -RemoteUrl $remote -ToolPackagePath $package -Execute;Assert ($r.Status -eq 'Installed');G $target @('config','user.name','Test Author')|Out-Null;G $target @('config','user.email','test@example.invalid')|Out-Null;$r=Install-StudyPublisher -Destination $target -RemoteUrl $remote -ToolPackagePath $package -Execute -ResumeInstallation -PublishBootstrap;Assert ($r.Status -eq 'Pushed') ($r.Errors -join ';');$files=G $target @('ls-tree','-r','--name-only','HEAD');Assert ($files -notmatch 'publisher.local.json|\.publish-state|LICENSE');Assert ($files -match 'README.md');Assert ($files -notmatch '数学/中文')}
 Check 'RejectRemoteBecameNonempty' {$f=GitFixture;$target=Join-Path $f.Base 'new';Reject {Install-StudyPublisher -Destination $target -RemoteUrl $f.Config.ExpectedRemote -ToolPackagePath $package -Execute};Assert (-not(Test-Path $target))}
 Check 'BootstrapCommitHookTamperStopsPush' {$f=Fixture;$remote=Join-Path $f.Base 'empty.git';G $f.Base @('init','--bare',$remote)|Out-Null;$target=Join-Path $f.Base 'new';Install-StudyPublisher -Destination $target -RemoteUrl $remote -ToolPackagePath $package -Execute|Out-Null;G $target @('config','user.name','Test Author')|Out-Null;G $target @('config','user.email','test@example.invalid')|Out-Null;WriteText (Join-Path $target '.git/hooks/pre-commit') "#!/bin/sh`nprintf 'tampered' >> README.md`ngit add README.md`n";$r=Install-StudyPublisher -Destination $target -RemoteUrl $remote -ToolPackagePath $package -Execute -ResumeInstallation -PublishBootstrap;Assert ($r.Status -eq 'CommittedNotPushed');Assert (-not(G $target @('ls-remote','origin','refs/heads/main')))}
 Check 'BootstrapPushDeniedKeepsInitialCommit' {$f=Fixture;$remote=Join-Path $f.Base 'empty.git';G $f.Base @('init','--bare',$remote)|Out-Null;WriteText (Join-Path $remote 'hooks/pre-receive') "#!/bin/sh`nexit 1`n";$target=Join-Path $f.Base 'new';$r=Install-StudyPublisher -Destination $target -RemoteUrl $remote -ToolPackagePath $package -Execute;G $target @('config','user.name','Test Author')|Out-Null;G $target @('config','user.email','test@example.invalid')|Out-Null;$r=Install-StudyPublisher -Destination $target -RemoteUrl $remote -ToolPackagePath $package -Execute -ResumeInstallation -PublishBootstrap;Assert ($r.Status -eq 'CommittedNotPushed');$id=G $target @('rev-parse','HEAD');WriteText (Join-Path $remote 'hooks/pre-receive') "#!/bin/sh`nexit 0`n";$r=Install-StudyPublisher -Destination $target -RemoteUrl $remote -ToolPackagePath $package -Execute -ResumeInstallation -PublishBootstrap;Assert ($r.Status -eq 'Pushed');Assert ($id -eq (G $target @('rev-parse','HEAD')))}
}
Write-Host "RESULT passed=$script:passed failed=$script:failed fixture=$runRoot"
if($script:failed){exit 1}








